name: gvxr-tutorials
channels:
    - conda-forge
    - https://software.repos.intel.com/python/conda
    - ccpi
dependencies:
    - ipyevents
    - ipympl
    - ipywidgets
    - jupyterlab
    - matplotlib
    - mpl-interactions
    - numpy
    - pandas
    - python=3.11
    - SimpleITK
    - cil
    - ccpi-regulariser
    - astra-toolbox=*=cuda*
    - tigre
    - progressbar
    - k3d
    - pip
    - pip:
        - viewscad
        - gvxr>=2.0.10